# Generated by Django 3.1.1 on 2020-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='printFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255)),
                ('colors', models.CharField(max_length=255)),
                ('nCopies', models.IntegerField()),
            ],
        ),
    ]
