# Generated by Django 3.1.1 on 2020-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printformmodel',
            old_name='colors',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='printformmodel',
            name='nCopies',
            field=models.PositiveIntegerField(),
        ),
    ]
