# Generated by Django 3.1.1 on 2020-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200911_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='printformmodel',
            name='File',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printformmodel',
            name='pages',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
