# Generated by Django 3.1.1 on 2020-09-13 09:05

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200913_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printformmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='printformmodel',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printformmodel',
            name='File',
            field=models.FileField(upload_to=main.utils.addDate),
        ),
    ]
